'use client'

import Link from 'next/link'
import { ArrowLeft, Bookmark, Heart, Send, Share2 } from 'lucide-react'
import { useState } from 'react'

const post = { author: 'Minh Anh', initials: 'MA', time: '2 giờ trước', title: 'Làm thế nào để xây dựng thói quen làm việc sâu?', tags: ['Năng suất', 'Thói quen'], paragraphs: ['Sau một thời gian làm việc phân tán, mình bắt đầu tìm hiểu về deep work và muốn biến nó thành một thói quen bền vững. Mình đã thử tắt thông báo, chia nhỏ lịch làm việc và để điện thoại ở phòng khác.', 'Điều hiệu quả nhất với mình là đặt một mục tiêu thật cụ thể cho mỗi phiên 90 phút, thay vì chỉ ghi chung chung là “làm dự án”. Mình rất muốn nghe thêm kinh nghiệm của mọi người: đâu là nghi thức bắt đầu giúp bạn vào guồng nhanh hơn?'] }
const initialComments = [{ id: 1, author: 'Bảo Ngọc', initials: 'BN', time: '1 giờ trước', text: 'Mình cũng thấy việc đặt mục tiêu cụ thể giúp bắt đầu dễ hơn rất nhiều.', replies: [] }, { id: 2, author: 'Đức Minh', initials: 'ĐM', time: '48 phút trước', text: 'Một mẹo nhỏ là tạo một danh sách “không làm” trong lúc deep work.', replies: [{ id: 3, author: 'Minh Anh', initials: 'MA', time: '30 phút trước', text: 'Danh sách “không làm” hay quá, mình sẽ thử ngay hôm nay.', replies: [] }] }]

function Avatar({ initials, small = false }) { return <div className={`flex shrink-0 items-center justify-center rounded-full bg-pink-200 font-bold text-pink-700 ${small ? 'size-9 text-xs' : 'size-10 text-xs'}`} aria-hidden="true">{initials}</div> }
function Comment({ comment, activeReply, setActiveReply }) { return <div><div className="flex gap-3"><Avatar initials={comment.initials} small /><div className="min-w-0 flex-1"><div className="rounded-2xl bg-white/60 px-4 py-3 dark:bg-pink-950/40"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{comment.author}</strong><span className="text-xs text-pink-700/50">{comment.time}</span></div><p className="mt-1 text-sm leading-6 text-pink-950/75 dark:text-pink-50/75">{comment.text}</p></div><div className="mt-1 px-3"><button type="button" onClick={() => setActiveReply(activeReply === comment.id ? null : comment.id)} className="text-xs font-semibold text-pink-700 hover:text-pink-500">Phản hồi</button></div>{activeReply === comment.id && <form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); setActiveReply(null) }}><input required className="min-w-0 flex-1 rounded-xl border border-white/50 bg-white/60 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-pink-400 dark:border-white/20 dark:bg-pink-950/40" placeholder="Viết phản hồi..." aria-label={`Phản hồi ${comment.author}`} /><button className="rounded-xl bg-pink-500 px-3 text-white hover:bg-pink-600" aria-label="Gửi phản hồi"><Send /></button></form>}</div></div>{comment.replies?.length > 0 && <div className="ml-8 mt-4 flex flex-col gap-4 border-l-2 border-pink-300 pl-4">{comment.replies.map((reply) => <Comment key={reply.id} comment={reply} activeReply={activeReply} setActiveReply={setActiveReply} />)}</div>}</div> }

export default function DiscussionDetailPage() { const [comments, setComments] = useState(initialComments); const [activeReply, setActiveReply] = useState(null); const [text, setText] = useState(''); const submit = (event) => { event.preventDefault(); if (!text.trim()) return; setComments((current) => [{ id: Date.now(), author: 'Bạn', initials: 'B', time: 'Vừa xong', text: text.trim(), replies: [] }, ...current]); setText('') }
 return <main className="min-h-screen px-4 py-8 text-pink-950 dark:text-pink-50 sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/thao-luan" className="sticky top-4 z-10 mb-6 inline-flex items-center gap-2 rounded-xl bg-white/60 px-4 py-2 text-sm font-semibold text-pink-700 shadow backdrop-blur hover:text-pink-500 dark:bg-pink-950/60"><ArrowLeft data-icon="inline-start" /> Quay lại diễn đàn</Link><article className="rounded-3xl border border-white/40 bg-white/40 p-6 shadow-xl backdrop-blur-xl dark:border-white/10 dark:bg-pink-900/40 sm:p-10"><div className="flex items-center gap-3"><Avatar initials={post.initials} /><div><strong className="text-sm">{post.author}</strong><p className="text-xs text-pink-700/60">{post.time} · Cộng đồng</p></div></div><h1 className="mt-6 text-3xl font-bold leading-tight sm:text-5xl">{post.title}</h1><div className="mt-5 flex gap-2">{post.tags.map((tag) => <span key={tag} className="rounded-full bg-pink-100 px-3 py-1 text-xs font-semibold text-pink-700 dark:bg-pink-800/60 dark:text-pink-100">#{tag}</span>)}</div><div className="mt-8 flex flex-col gap-5 text-base leading-8 text-pink-950/80 dark:text-pink-50/80">{post.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-8 flex flex-wrap gap-2 border-t border-white/30 pt-5"><button className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold hover:bg-pink-100/70"><Heart /> Thích</button><button className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold hover:bg-pink-100/70"><Bookmark /> Lưu</button><button className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold hover:bg-pink-100/70"><Share2 /> Chia sẻ</button></div><hr className="my-8 border-white/30" /><section><h2 className="text-2xl font-bold">Bình luận <span className="text-pink-500">({comments.length})</span></h2><form onSubmit={submit} className="mt-5 flex gap-3"><Avatar initials="B" /><div className="flex min-w-0 flex-1 gap-2"><textarea required value={text} onChange={(event) => setText(event.target.value)} rows={2} placeholder="Chia sẻ suy nghĩ của bạn..." className="min-w-0 flex-1 resize-none rounded-xl border border-white/50 bg-white/60 p-3 text-sm outline-none focus:ring-2 focus:ring-pink-400 dark:border-white/20 dark:bg-pink-950/40" /><button className="self-end rounded-xl bg-pink-500 px-4 py-3 font-semibold text-white hover:bg-pink-600">Bình luận</button></div></form><div className="mt-8 flex flex-col gap-6">{comments.map((comment) => <Comment key={comment.id} comment={comment} activeReply={activeReply} setActiveReply={setActiveReply} />)}</div></section></article></div></main> }
