import Link from 'next/link'
import { ArrowLeft, ArrowRight, FileText, Sparkles } from 'lucide-react'
import { getCategory, getTemplatesByCategory } from '@/data/mockData'

function PdfThumbnail({ template }) {
  return <div className="relative h-56 w-full overflow-hidden rounded-xl border border-border bg-white p-5 shadow-inner sm:w-44 sm:shrink-0"><div className="text-center text-[8px] font-bold tracking-wide text-slate-800">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div><div className="mx-auto mt-1 h-px w-20 bg-slate-300" /><div className="mt-5 text-center text-[11px] font-bold text-slate-900">{template.title.replace('Đơn xin ', '').toUpperCase()}</div><div className="mt-4 flex flex-col gap-2">{[1, 2, 3, 4, 5].map((line) => <span key={line} className={`h-1.5 rounded bg-slate-200 ${line === 3 ? 'w-3/4' : 'w-full'}`} />)}</div><div className="absolute bottom-5 right-5 flex size-7 items-center justify-center rounded-full bg-slate-100"><FileText size={13} className="text-slate-500" /></div><span className="absolute right-2 top-2 rounded bg-slate-900/5 px-1.5 py-0.5 text-[8px] font-semibold text-slate-400">PDF</span></div>
}

export default async function TemplatesPage({ params }) {
  const { categoryId } = await params
  const category = getCategory(categoryId)
  const templates = getTemplatesByCategory(categoryId)
  if (!category) return <main className="flex min-h-screen items-center justify-center bg-background"><div className="text-center"><p className="text-muted-foreground">Không tìm thấy danh mục.</p><Link href="/" className="mt-3 inline-block font-semibold text-primary">Về trang chủ</Link></div></main>
  return <div className="min-h-screen bg-pink-50/40 text-pink-950"><header className="border-b border-white/50 bg-white/40 backdrop-blur-xl backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft size={17} /> Tất cả danh mục</Link><Link href="/" className="text-lg font-semibold tracking-tight">Formly</Link><span className="hidden items-center gap-1.5 text-xs text-muted-foreground sm:flex"><Sparkles size={14} className="text-primary" /> Mẫu chuẩn hóa</span></div></header><main className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">{category.title}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Chọn mẫu phù hợp với bạn</h1><p className="mt-3 text-muted-foreground">Xem trước bản PDF trước khi điền thông tin. Mỗi mẫu đã được thiết kế sẵn để bạn hoàn thành nhanh chóng.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{templates.length ? templates.map((template, index) => <article key={template.id} className="group flex flex-col overflow-hidden rounded-2xl border border-white/50 bg-white/40 shadow-2xl backdrop-blur-xl transition-all hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-center bg-pink-100/40 p-5"><PdfThumbnail template={template} /></div><div className="flex flex-1 flex-col p-5"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold text-foreground">{template.title}</h2>{index === 0 && <span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-primary">Phổ biến</span>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{template.description}</p><p className="mt-auto pt-4 text-xs text-muted-foreground">{template.updated}</p><Link href={`/form/${template.id}`} className="mt-4 inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition hover:opacity-90">Chọn mẫu này <ArrowRight size={16} /></Link></div></article>) : <div className="col-span-full rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground">Danh mục này chưa có mẫu.</div>}</div></main></div>
}
